browser=chrome
headless=false
base.url=https://www.saucedemo.com
api.base.url=https://jsonplaceholder.typicode.com
default.timeout.seconds=15
retry.count=1
standard.user.username=standard_user
standard.user.password=secret_sauce